# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
# - name: "[TITLE]"

# - title: "[TITLE]"
# - description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
# - base# - url: "[PATH]" # e.g. /manton or /az/azasdfasdf
# - url: "http://[HOSTNAME]" # the base hostname & protocol for your site
# - markdown: kramdown
# - user# - name: "[USERNAME]"

# Navigation
nav:
  - # - name:           "About"
    href:           "/about/"
  - # - name:           "RSS"
    href:           "/feed.xml"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Des Paroz"
tagline: ""
description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
credits: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
baseurl: ""
url: "http://desparoz.me"
markdown: "kramdown"
username: "desparoz"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Des Paroz"
name: "Des Paroz"
gravatar_hash: "ff81688107f77a63a34f68e536aeca77"
avatar: "https://www.gravatar.com/avatar/ff81688107f77a63a34f68e536aeca77?s=160"
full_name: "Des Paroz"
bio: ""
twitter_username: "desparoz"
github_username: "desparoz"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Pacific/Yap"